# Generated by Django 5.0.1 on 2024-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
